sudo: false # use containers

language: java

# Makes build faster to cache maven things.
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  
services:
  - docker

jdk:
 - oraclejdk8

install:
  - cd $HOME && rm -rf JanuaryTests && git clone https://github.com/jonahkichwacoders/JanuaryTests.git && cd -
  
# verify does everything, including tests, but excludes the install step
script: 
 - mvn verify

